;reverse input
.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC  
    ;DISPLAY USER PROMPT
    MOV AH,2    ;PREPARE TO DISPLAY
    MOV DL,'?'
    INT 21H   
    
    ;INITIALIZE CHARACTER COUNT
    XOR CX,CX   ;COUNT=0
    
    ;READ CHARACTER
    MOV AH,1
    INT 21H
    
    ;WHILE A CHARACTER IS NOT A CARRIAGE RETURN
WHILE:
    CMP AL,0DH      ;CR(Carriage Return)
    JE ENDWHILE     ;YES,JUMP TO EXIT LOOP
    
    ;SAVE CHARACTER ON STACK AND INCREMENT COUNT
    PUSH AX         ;PUSH IT ON STACK
    INC CX          ;COUNT++
    
    ;READ A CHARACTER
    INT 21H         ;READ A CHARACTER
    JMP WHILE       ;LOOP BACK
    
ENDWHILE:
    ;NEW LINE
    MOV AH,2        ;DISPLAY CHAR FUNC
    MOV DL,10       ;LINE FEED
    INT 21H         ;EXECUTE
    MOV DL,13       ;CR
    INT 21H         ;EXECUTE
    JCXZ EXIT       ;JUMP IF NO CHARACTER READ
;FOR COUNT TIMES DO
TOP:
;POP A CHARACTER FROM THE STACK
    POP DX          ;GET CHARACTER FROM STACK
;DISPLAY IT
    INT 21H         ;EXECUTE
    LOOP TOP        ;LOOP BACK
;END FOR
EXIT:
     MOV AH,4CH
     INT 21H
MAIN ENDP
END MAIN