;UVA 10970 - Big Chocolate
;Author: Fahim Rahman

INCLUDE EMU8086.INC
.MODEL SMALL
.STACK 100H
.DATA
ROW DW ?
COL DW ?
.CODE
MAIN PROC
    ;INITIALIZE DATA DEGMENT
    MOV AX,@DATA
    MOV DS,AX
    
WHILELOOP:
    CALL SCAN_NUM
    MOV ROW,CX
    PRINTN
    CALL SCAN_NUM
    MOV COL,CX
    PRINTN    ;NEW LINE
    MOV AX,ROW
    MUL CX  ;ROW*COL
    SUB AX,1    ;T-1
    CALL PRINT_NUM
    PRINTN
    JMP WHILELOOP    
    
    
    ;RETURN TO DOS
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
    DEFINE_SCAN_NUM
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS
END MAIN