;UVA 1124 - Celebrity Jeopardy
;Author: Fahim Rahman

INCLUDE EMU8086.INC

.MODEL SMALL
.STACK 100H
.DATA
STR DB 20 DUP(?)
.CODE
MAIN PROC
LOOOP:
   ;BX IS FOR USING ARRAY INDEX
   MOV BX,0   
INPUT:
   ;INPUT A ELEMENT
   MOV AH,1
   INT 21H
   ;IF 'ENTER' THEN STOP ENTERING
   CMP AL,13
   JE ENDINPUT
   ;ELSE SAVE IT TO ARRAY
   MOV STR[BX],AL
   INC BX
JMP INPUT

ENDINPUT:
   PRINTN       ;DEFAULT NEW LINE 
   ;HAVE TO PRINT FROM 1ST INDEX
   MOV SI,0

OUTPUT:
    CMP SI, BX
    JE ENDLOOP
    ;LOAD A ELEMENT TO PRINT  
    MOV DL, STR[SI]
    MOV AH,2
    INT 21H
    ;INCREMENT INDEX TO PRINT
    INC SI
    JMP OUTPUT  

ENDLOOP:
    PRINTN
    JMP LOOOP   ;INFINITE LOOP
    
    
    ;RETURN TO DOS
    MOV AH, 4CH
    INT 21H
    
    MAIN ENDP
END MAIN