;UVA 10079 - Pizza Cutting
;Author: Fahim Rahman

INCLUDE EMU8086.INC

.MODEL SMALL
.STACK 100H
.DATA
TESTCASE DW ?
VALUE DW ?
ADDD DW ?
.CODE
MAIN PROC
    ;INITIALIZA DATA SEGMENT
    MOV AX,@DATA
    MOV DS,AX
    
WHILELOOP:
    
    CALL SCAN_NUM   ;TEST
    MOV TESTCASE,CX
    PRINTN 
    CMP CX,0
    JL EXIT     ;IF(TEST<0) THEN BREAK
    ;ELSE 
    MOV CX,TESTCASE
    MOV ADDD,CX
    ADD ADDD,1  ;TEST+1
    MOV AX,TESTCASE
    MOV CX,ADDD 
    MUL CX      ;TEST*((TEST+1)
    MOV CX,2
    DIV CX      ;(TEST*((TEST+1))/2 
    MOV CX,TESTCASE
    ADD AX,1 
    
    CALL PRINT_NUM
    PRINTN
    JMP WHILELOOP
    
    
EXIT:    
    ;RETURN TO DOS
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
    DEFINE_SCAN_NUM
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS
END MAIN
